### ISSUE TITLE
extention doesn't work with proxy zabbix servers

### ISSUE THREAD

**Issue by sun4ezzz** [zarplata/zabbix-agent-extension-elasticsearch#26]
Hello!

We have a huge infrastructure to monitor with our Zabbix server so we use several proxy servers for load balancing purposes. And main Zabbix server is closed for monitored hosts.
Is it possible to configure this extension to send data via proxy server? 

Thank you.

**Comment by rugenl** [comment]
Yes, if I understand what you're asking, the macro {$ZABBIX_SERVER_IP} really refers to the server or proxy for reporting zabbix items.  It's like the -z option on zabbix_sender.


Len Rugen

rugenl at yahoo.com


 

    On Wednesday, October 23, 2019, 06:31:47 AM CDT, sun4ezzz <notifications@github.com> wrote:  
 
 
Hello!

We have a huge infrastructure to monitor with our Zabbix server so we use several proxy servers for load balancing purposes. And main Zabbix server is closed for monitored hosts.
Is it possible to configure this extension to send data via proxy server?

Thank you.

**Comment by sun4ezzz** [comment]
Yes, I tried to set the macro {$ZABBIX_SERVER_IP}  to proxy server but no data was published to Zabbix.
Did you configure the same?

Thank you.

**Comment by rugenl** [comment]
Yes, it's working here, but it's been awhile since I installed it.  I don't remember any problems.  I have multiple elastic clusters reporting to 2 different proxies.


On October 23, 2019, at 10:45 AM, sun4ezzz <notifications@github.com> wrote:

Yes, I tried to set the macro {$ZABBIX_SERVER_IP} to proxy server but no data was published to Zabbix.
Did you configure the same?

Thank you.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/zarplata/zabbix-agent-extension-elasticsearch/issues/26?email_source=notifications">https://github.com/zarplata/zabbix-agent-extension-elasticsearch/issues/26?email_source=notifications</a>\u0026email_token=AAWILEUXAZISI7I5KVMTDYLQQBWP3A5CNFSM4JD76AH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECB4T5I#issuecomment-545507829", "url": "<a href="https://github.com/zarplata/zabbix-agent-extension-elasticsearch/issues/26?email_source=notifications">https://github.com/zarplata/zabbix-agent-extension-elasticsearch/issues/26?email_source=notifications</a>\u0026email_token=AAWILEUXAZISI7I5KVMTDYLQQBWP3A5CNFSM4JD76AH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECB4T5I#issuecomment-545507829", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by sun4ezzz** [comment]
Fixed the issue. Just be sure to set macro {$ZABBIX_SERVER_IP} to the same proxy server as in "Monitored by proxy" field in Host configuration.
